eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka2:8762/,http://${spring.security.user.name}:${spring.security.user.password}@eureka3:8763/
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
spring:
  application:
    name: eureka
  security:
    basic:
      enable: true #开启基于HTTP basic的认证
    user: #配置用户的账号信息
      name: root
      password: root
server:
  port: 8761
  servlet:
    context-path: /